### ISSUE TITLE
Connection handling

### ISSUE THREAD

**Issue by mattheworiordan** [ably/demo-mobile-android#2]
I just tried the demo, but it was in Airplane mode, however I would have expected an error to be displayed to the user, instead it remains trying, and I sere the following in the logs.

I would expect a failure by the client library to obtain a token to result in the connection becoming failed which should show a notice to the user on the home page (i.e. show the reason of the failed state change) and then allow them to try again.  If this is a client library issue per se, please add an issue there./

```
04-01 12:18:35.030 2155-2155/com.ablydemo I/System.out: (INFO): io.ably.lib.realtime.AblyRealtime: started
04-01 12:18:35.030 2155-2155/com.ablydemo I/System.out: (INFO): Auth(): using token auth with authUrl
04-01 12:19:05.040 2155-2887/com.ablydemo I/System.out: (VERBOSE): io.ably.lib.transport.ConnectionManager: requestState(): requesting connecting; id = null
04-01 12:19:05.040 2155-2887/com.ablydemo I/System.out: (VERBOSE): io.ably.lib.transport.ConnectionManager: notifyState(): notifying connecting; id = null
04-01 12:19:05.040 2155-2887/com.ablydemo I/System.out: (INFO): TokenAuth.authorise(): 
04-01 12:19:05.040 2155-2887/com.ablydemo I/System.out: (INFO): TokenAuth.authorise(): requesting new token
04-01 12:19:05.040 2155-2887/com.ablydemo I/System.out: (INFO): Auth.requestToken(): using token auth with auth_url
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out: (ERROR): io.ably.lib.transport.WebSocketTransport: Unexpected exception attempting connection; wsUri = wss://realtime.ably.io:443/
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out: io.ably.lib.types.AblyException$HostFailedException: java.net.UnknownHostException: Unable to resolve host "www.ably.io": No address associated with hostname
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at io.ably.lib.http.Http.httpExecute(Http.java:331)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at io.ably.lib.http.Http.getUri(Http.java:194)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at io.ably.lib.rest.Auth.requestToken(Auth.java:381)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at io.ably.lib.http.TokenAuth.authorise(TokenAuth.java:54)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at io.ably.lib.rest.Auth.authorise(Auth.java:325)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at io.ably.lib.rest.Auth.getAuthParams(Auth.java:539)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at io.ably.lib.transport.WebSocketTransport.connect(WebSocketTransport.java:59)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at io.ably.lib.transport.ConnectionManager.connectImpl(ConnectionManager.java:614)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at io.ably.lib.transport.ConnectionManager.handleStateRequest(ConnectionManager.java:421)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at io.ably.lib.transport.ConnectionManager.run(ConnectionManager.java:529)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at java.lang.Thread.run(Thread.java:818)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out: Caused by: java.net.UnknownHostException: Unable to resolve host "www.ably.io": No address associated with hostname
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at java.net.InetAddress.lookupHostByName(InetAddress.java:457)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at java.net.InetAddress.getAllByName(InetAddress.java:215)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at com.android.okhttp.HostResolver$1.getAllByName(HostResolver.java:29)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:232)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:124)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:272)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:500)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at io.ably.lib.http.Http.readResponse(Http.java:408)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at io.ably.lib.http.Http.httpExecute(Http.java:329)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     ... 10 more
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out: Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at libcore.io.Posix.android_getaddrinfo(Native Method)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     at java.net.InetAddress.lookupHostByName(InetAddress.java:438)
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out:     ... 24 more
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out: (VERBOSE): io.ably.lib.transport.ConnectionManager: notifyState(): notifying disconnected; id = null
04-01 12:19:05.050 2155-2887/com.ablydemo I/System.out: (VERBOSE): io.ably.lib.transport.ConnectionManager: setState(): setting disconnected
```

**Comment by stannedelchev** [comment]
OK, I'll look into fixing this. We don't really handle connection issues on the home screen.

**Comment by stannedelchev** [comment]
OK, I pushed a fix for this in `main`, you can check it out.
Now when we have an error, a toast notification is displayed to the user. The lib automatically retries in 30 seconds from what I can see.

**Comment by mattheworiordan** [comment]
Thanks @stannedelchev I will review soon

**Comment by funkyboy** [comment]
Toast message is shown correctly when in airplane mode. Closing.
