### ISSUE TITLE
Version not support on a physical device & actual device

### ISSUE THREAD

**Issue by mattheworiordan** [ably/demo-mobile-android#3]
Here is the error I get when trying the demo. This is filed as a Java lib issue too at https://github.com/ably/ably-java/issues/124, however I had incorrectly assumed it was only a problem on physical devices,  it seems your recent changes have resulted in this error every time.

```
(INFO): Auth.requestToken(): using token auth with auth_url
04-01 12:22:20.420 2155-6126/com.ablydemo I/System.out: (ERROR): io.ably.lib.http.Http: Error response from server: statusCode = 505; statusLine = HTTP Version Not Supported
04-01 12:22:20.420 2155-6126/com.ablydemo I/System.out: (ERROR): io.ably.lib.transport.WebSocketTransport: Unexpected exception attempting connection; wsUri = wss://realtime.ably.io:443/
04-01 12:22:20.420 2155-6126/com.ablydemo I/System.out: io.ably.lib.types.AblyException: java.lang.Exception: HTTP Version Not Supported
04-01 12:22:20.420 2155-6126/com.ablydemo I/System.out:     at io.ably.lib.http.Http.httpExecute(Http.java:383)
04-01 12:22:20.420 2155-6126/com.ablydemo I/System.out:     at io.ably.lib.http.Http.getUri(Http.java:194)
04-01 12:22:20.420 2155-6126/com.ablydemo I/System.out:     at io.ably.lib.rest.Auth.requestToken(Auth.java:381)
04-01 12:22:20.420 2155-6126/com.ablydemo I/System.out:     at io.ably.lib.http.TokenAuth.authorise(TokenAuth.java:54)
04-01 12:22:20.420 2155-6126/com.ablydemo I/System.out:     at io.ably.lib.rest.Auth.authorise(Auth.java:325)
04-01 12:22:20.420 2155-6126/com.ablydemo I/System.out:     at io.ably.lib.rest.Auth.getAuthParams(Auth.java:539)
04-01 12:22:20.420 2155-6126/com.ablydemo I/System.out:     at io.ably.lib.transport.WebSocketTransport.connect(WebSocketTransport.java:59)
04-01 12:22:20.420 2155-6126/com.ablydemo I/System.out:     at io.ably.lib.transport.ConnectionManager.connectImpl(ConnectionManager.java:614)
04-01 12:22:20.420 2155-6126/com.ablydemo I/System.out:     at io.ably.lib.transport.ConnectionManager.handleStateRequest(ConnectionManager.java:421)
04-01 12:22:20.420 2155-6126/com.ablydemo I/System.out:     at io.ably.lib.transport.ConnectionManager.run(ConnectionManager.java:529)
04-01 12:22:20.420 2155-6126/com.ablydemo I/System.out:     at java.lang.Thread.run(Thread.java:818)
04-01 12:22:20.420 2155-6126/com.ablydemo I/System.out: Caused by: java.lang.Exception: HTTP Version Not Supported
04-01 12:22:20.420 2155-6126/com.ablydemo I/System.out:     ... 11 more
04-01 12:22:20.420 2155-6126/com.ablydemo I/System.out: (VERBOSE): io.ably.lib.transport.ConnectionManager: notifyState(): notifying disconnected; id = null
04-01 12:22:20.420 2155-6126/com.ablydemo I/System.out: (VERBOSE): io.ably.lib.transport.ConnectionManager: setState(): setting disconnected
```

**Comment by stannedelchev** [comment]
I updated the Ably library in the demo and was not able to reproduce this issue in a few runs. Would you get the latest from `main` and try again, please?

**Comment by mattheworiordan** [comment]
Ok, will try again shortly

**Comment by mattheworiordan** [comment]
This is no longer an issue
